language: python
sudo: false

services:
  - mongodb

python:
  - 3.4
  - 3.5

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - conda config --set show_channel_urls True
  - conda config --set always_yes True
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda
  - conda create -n testenv nose python=$TRAVIS_PYTHON_VERSION scipy requests matplotlib jsonschema traitlets pytest
  - source activate testenv
  - pip install pytest-cov pytest-xdist
  - conda install metadatastore databroker historydict boltons prettytable doct toolz tifffile -c lightsource2 -c conda-forge -c soft-matter
  - conda remove metadatastore databroker filestore --yes
  - conda install super_state_machine cycler xray-vision lmfit -c tacaswell
  - 'pip install https://github.com/NSLS-II/databroker/zipball/master#egg=databroker'
  - 'pip install https://github.com/NSLS-II/filestore/zipball/master#egg=filestore'
  - 'pip install https://github.com/NSLS-II/metadatastore/zipball/master#egg=metadatastore'
  - conda install pymongo pcaspy pyepics readline -c tacaswell
  - pip install coveralls
  - python setup.py install
  # Need to clean the python build directory (and other cruft) or pytest is
  # going to find the build directory and get confused why there are two sets
  # of every test file
  - git clean -xfd

script:
  - python run_tests.py --cov bluesky -vrxs
