language: python
sudo: false
env:
  global:
    BUILD_DOCS_BRANCH: master
    DOCS_SUBDIR: doc/
    TARGET_DEV_SUBDIR: bluesky/
    HTML_SUBDIR: build/html
    DOCS_CONDA_DEPS: "bluesky"
    DOCS_PIP_DEPS: "tqdm"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  include:
    - python: 3.6
      env: BUILD_DOCS=true
    - python: 3.5
      env: BUILD_DOCS=false CONDA_ENV=1
    - python: 3.5
      env: BUILD_DOCS=false CONDA_ENV=1 EXTRA_C_CHAN='-c lightsource2-dev'
    - python: 3.6
      env: BUILD_DOCS=false CONDA_ENV=1

before_install:
  - git clone https://github.com/NSLS-II/nsls2-ci --branch master --single-branch ~/ci_scripts
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - |
    if [ $CONDA_ENV ]; then
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
       chmod +x miniconda.sh
       ./miniconda.sh -b -p /home/travis/mc
       export PATH=/home/travis/mc/bin:$PATH
       conda config --set show_channel_urls True
       conda config --set always_yes True
    fi
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - |
    if [ $CONDA_ENV ]; then
       conda create -n testenv python=$TRAVIS_PYTHON_VERSION scipy matplotlib numpy h5py traitlets jsonschema databroker pip doct xray-vision lmfit pyzmq ophyd filestore event-model dill boltons ophyd pims mongoquery pytest $EXTRA_C_CHAN -c lightsource2-tag -c conda-forge -c soft-matter -c defaults --override-channels
       source activate testenv
       pip install https://github.com/NSLS-II/portable-mds/zipball/master#egg=portable_mds
       pip install https://github.com/NSLS-II/event-model/zipball/master#egg=event_model
       source activate testenv
    else
       pip install -r requirements.txt
       pip install -r test-requirements.txt
    fi
  - pip install codecov
  - python setup.py install
  # Need to clean the python build directory (and other cruft) or pytest is
  # going to find the build directory and get confused why there are two sets
  # of every test file
  - python -c "from filestore import utils, conf; utils.install_sentinels(conf.connection_config, 1)"
  # make sure the sqlite file exists to avoid race conditions
  - python -c "from bluesky.utils import get_history; get_history()"
  - git clean -xfd

script:
  - coverage run run_tests.py
  - coverage report -m
  - |
    if [ $BUILD_DOCS == true ]; then
      conda install --no-deps -c conda-forge/label/rc matplotlib  # mpl 2.x
      source ~/ci_scripts/make-docs.sh
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'NSLS-II/bluesky' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      echo "Adding encrypted deployment key for uploading docs"
      openssl aes-256-cbc -K $encrypted_5e70d93e51c3_key -iv $encrypted_5e70d93e51c3_iv -in bluesky-docs-deploy.enc -out bluesky-docs-deploy -d
      eval `ssh-agent -s`
      chmod 600 bluesky-docs-deploy
      ssh-add bluesky-docs-deploy
      source ~/ci_scripts/push-docs.sh
    fi
