language: python
sudo: false

services:
  - mongodb

python:
  - 3.5

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda create -n testenv --yes nose python=$TRAVIS_PYTHON_VERSION scipy requests matplotlib jsonschema traitlets
  - source activate testenv
  - conda install --yes metadatastore databroker historydict boltons prettytable doct -c lightsource2 -c conda-forge -c soft-matter
  - conda remove metadatastore databroker filestore --yes
  - conda install --yes super_state_machine cycler xray-vision lmfit -c tacaswell
  - 'pip install https://github.com/NSLS-II/databroker/zipball/master#egg=databroker'
  - 'pip install https://github.com/NSLS-II/filestore/zipball/master#egg=filestore'
  - 'pip install https://github.com/tacaswell/metadatastore/zipball/API_match_mds_schema#egg=metadatastore'
  - conda install --yes pymongo pcaspy pyepics readline -c tacaswell
  - pip install coveralls
  - python setup.py install

script:
  - python run_tests.py -v
