# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Test'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda update conda --yes
      conda create --yes --quiet --name bluesky python=$(python.version)
    displayName: Create Anaconda environment

  - script: |
      conda activate bluesky
      conda install -c anaconda qt sqlite
      conda install matplotlib pyqt
    displayName: Install Anaconda packages

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r dev-requirements.txt
      pip install .
    displayName: Install dependencies

  - script: |
      set MPLBACKEND=Qt5Agg
      pytest bluesky/tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: pytest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
